"""This data was downloaded from https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Grocery_and_Gourmet_Food_5.json.gz and unzipped manually.

    The following python was then run on the unzipped file, to result in what you see under AMAZON_REVIEWS:
    ```
    import json, collections
    with open("/Users/britz/Downloads/Grocery_and_Gourmet_Food_5.json",) as fil:
        lines = fil.read().split('\n')

    AMAZON_REVIEWS = []
    for line in lines:
        try:
            review = json.loads(line)
        except json.JSONDecodeError:
            pass
        else:
            if review['asin'] == 'B0009JQK9C':
                AMAZON_REVIEWS.append(review)


    ```
    For more information on the original dataset, see: https://nijianmo.github.io/amazon/index.html
"""

AMAZON_REVIEWS = [
    {
        "overall": 5.0,
        "vote": "6",
        "verified": True,
        "reviewTime": "04 23, 2014",
        "reviewerID": "A1KIX30V06V70I",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Kiyenna Kurayami",
        "reviewText": "My mom was sad when she couldn't find her favorite ginger tea at stores anymore. She tried several and none of them were as good. I got her this on Amazon and it's the only one she's happy with. Yay!",
        "summary": "Good ginger tea",
        "unixReviewTime": 1398211200,
    },
    {
        "overall": 5.0,
        "vote": "3",
        "verified": True,
        "reviewTime": "05 5, 2013",
        "reviewerID": "A11PMRVCA3TCXC",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Happy Mamaw",
        "reviewText": "I originally got this tea, because I love ginger root. This spicy tea is marvelous for nausea. This product shipped out the same day, and I received it within a few days. Thanks for such a great tea!",
        "summary": "Organic Ginger Tea...simply amazing!",
        "unixReviewTime": 1367712000,
    },
    {
        "overall": 5.0,
        "vote": "4",
        "verified": True,
        "reviewTime": "03 21, 2013",
        "reviewerID": "A24JK19TJDW77L",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Patti A. McBride",
        "reviewText": "This tea is fabulous.  It is great for the digestive system, & I have been using it for several years.",
        "summary": "Organic Ginger Tea",
        "unixReviewTime": 1363824000,
    },
    {
        "overall": 5.0,
        "vote": "20",
        "verified": False,
        "reviewTime": "01 25, 2012",
        "reviewerID": "A100ZQDV7L8PVV",
        "asin": "B0009JQK9C",
        "reviewerName": "Herblady22",
        "reviewText": 'Ginger tea is warming, carminative (spicy in a way that helps you digest better) and prevents the feeling of nausea.  I used it during pregnancy and recommend it to my clients.  It also helps when food seems to sit in your stomach, repeat on you and your digestion is sluggish.  It is anti-infective if you let it steep enough- say 15 minutes and can be used for colds with clear or white mucous.  And ginger is anti-inflammatory so can help with aches and pains.\n\nJust be aware that if you have an acid stomach, tend to run hot, have heartburn or yellow-green phlegm that&nbsp;<a data-hook="product-link-linked" class="a-link-normal" href="/Traditional-Medicinals-Organic-Peppermint-16-Count-Pack-of-6/dp/B0009F3PJ4/ref=cm_cr_arp_d_rvw_txt?ie=UTF8">Traditional Medicinals Organic Peppermint, 16-Count (Pack of 6)</a>&nbsp;tea may be a better bet.',
        "summary": "Good for cold indigestion or morning sickness",
        "unixReviewTime": 1327449600,
    },
    {
        "overall": 4.0,
        "vote": "3",
        "verified": True,
        "reviewTime": "05 4, 2011",
        "reviewerID": "A1ZK5P0EOE727F",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Denise M. Everett",
        "reviewText": "I really like this tea, I started drinking it at the suggestion of a friend.\nIt helps to sooth an upset stomache. I will be buying it again in the future.",
        "summary": "This is great tea.",
        "unixReviewTime": 1304467200,
    },
    {
        "overall": 5.0,
        "verified": False,
        "reviewTime": "02 18, 2018",
        "reviewerID": "A3L5PEHPMY8T4A",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "DesertFox",
        "reviewText": "I had nausea during my miscarriage and this tea helped greatly. Better than pepto even. They no longer carry this at the store by me! But it's the only ginger tea without a bunch of other herbs in it. Some of those other herbs can give side effects that I definitely do not want or need right now. Ypu have to be careful with some of those...",
        "summary": "Only ginger tea I've found without a bunch of other unwanted herbs",
        "unixReviewTime": 1518912000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "02 8, 2018",
        "reviewerID": "ATG7P4G02YKWQ",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Chemy",
        "reviewText": "Very good!",
        "summary": "Best Ginger tea",
        "unixReviewTime": 1518048000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 12, 2018",
        "reviewerID": "AKO9SQ6XREB5",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Country girl",
        "reviewText": "I just reordered because I really liked it.  Lots of ginger kick.  I do grate my own ginger for tea, but when I'm too lazy or in a hurry, these tea bags work great.  I have also noticed a definite decline in stiff fingers and knees during this awful damp, cold winter.",
        "summary": 'A good sharp ginger "kick" and anti-inflammatory too',
        "unixReviewTime": 1515715200,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "01 10, 2018",
        "reviewerID": "A23FVPGB0Y95QW",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Linda Howard Fan",
        "reviewText": "excellent product and service",
        "summary": "Four Stars",
        "unixReviewTime": 1515542400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 4, 2018",
        "reviewerID": "A2CZV7FR72CC30",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Ellen",
        "reviewText": "Great taste. Great for upset stomachs.",
        "summary": "Five Stars",
        "unixReviewTime": 1515024000,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "12 14, 2017",
        "reviewerID": "A37MC48LDDI5VQ",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Lew Harrison.",
        "reviewText": "VERY STROONG",
        "summary": "Four Stars",
        "unixReviewTime": 1513209600,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "11 9, 2017",
        "reviewerID": "AANUATFQFWADY",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "T. Lewis",
        "reviewText": "It's alkaline so I like this for my body....",
        "summary": "It's alkaline baby!!",
        "unixReviewTime": 1510185600,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "11 3, 2017",
        "reviewerID": "A3UITGYJ4UAD2F",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Traci",
        "reviewText": "Good flavor. Works great for upset stomach.",
        "summary": "Tastes good",
        "unixReviewTime": 1509667200,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "10 23, 2017",
        "reviewerID": "A3MPBKL3377FW8",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Amazon Customer",
        "reviewText": "GREAT PRODUCT, FAST DELIVERY, THANK YOU WILL ORDER AGAIN SOON .",
        "summary": "Five Stars",
        "unixReviewTime": 1508716800,
    },
    {
        "overall": 5.0,
        "verified": False,
        "reviewTime": "09 16, 2017",
        "reviewerID": "A38PLEIMX50DW9",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "ash felk",
        "reviewText": "I love the TM brand. All their teas are great and fully organic. I have a lot of stomach issues and I have tried several brands of ginger tea. TM seems to work the best at easing nausea for me. Their peppermint tea is great as well.",
        "summary": "I love the TM brand",
        "unixReviewTime": 1505520000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "05 23, 2017",
        "reviewerID": "AVVBWZRPWS0QL",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "stpatsbaby",
        "reviewText": "Really liked this tea.",
        "summary": "Five Stars",
        "unixReviewTime": 1495497600,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "05 20, 2017",
        "reviewerID": "A2VTBXPAYMNS2D",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Not a Purist",
        "reviewText": "I only drink herbal tea. Ginger is one of my favorites.",
        "summary": "Fav",
        "unixReviewTime": 1495238400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "04 29, 2017",
        "reviewerID": "A3QT0NEZYDYV2H",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Amazon Customer",
        "reviewText": "Excellent product for digestion before or after meals. Soothing and not to spicy.",
        "summary": "Five Stars",
        "unixReviewTime": 1493424000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "04 24, 2017",
        "reviewerID": "A3730HRYWZLP23",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "jay",
        "reviewText": "exellent",
        "summary": "exellent",
        "unixReviewTime": 1492992000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "04 18, 2017",
        "reviewerID": "A2E30DZ38JDPC2",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Melissa",
        "reviewText": "Execllent. I ordered some and sent to my brother when he was sick, he loves it too.",
        "summary": "Five Stars",
        "unixReviewTime": 1492473600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "03 30, 2017",
        "reviewerID": "A1P44U20RC3DM0",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Amazon Customer",
        "reviewText": ";)",
        "summary": "Five Stars",
        "unixReviewTime": 1490832000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "03 16, 2017",
        "reviewerID": "A32MROU56EQRYS",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "college student",
        "reviewText": "This takes a while to steep but is fully worth the wait. It gets very strong. I drink it for my stomach.",
        "summary": "This takes a while to steep but is fully worth ...",
        "unixReviewTime": 1489622400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "03 1, 2017",
        "reviewerID": "A13IDW4VYV4V9W",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "TWalliczek",
        "reviewText": "I have bought this tea a few times now and use it for reflux and upset stomach. It's great tea, tastes good and I find myself relaxing with it. Definitely a great flavor without being overwhelming.",
        "summary": "Excellent tea",
        "unixReviewTime": 1488326400,
    },
    {
        "overall": 5.0,
        "vote": "6",
        "verified": True,
        "reviewTime": "03 1, 2017",
        "reviewerID": "A2IZLMCA9GOIZ0",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "JB",
        "reviewText": "Great!!\nBought for husband's acid reflux, he's been drinking a cup in the morning and one in the evening and has gotten sooo much relief! Thanks for a great product! Ordering more soon!!!",
        "summary": "Great for acid reflux!",
        "unixReviewTime": 1488326400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "02 23, 2017",
        "reviewerID": "A1W7O7FJ8K07WN",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Patty",
        "reviewText": "I love this tea.  Very soothing.",
        "summary": "Five Stars",
        "unixReviewTime": 1487808000,
    },
    {
        "overall": 1.0,
        "verified": True,
        "reviewTime": "02 12, 2017",
        "reviewerID": "A2LZCWGSG04DDB",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Mike of LOFS",
        "reviewText": "Crushes box to fit in letter envelope, plan on getting it all smashed. After brewing twice what bags were salvageable, no taste to tea or change in color. I threw it away.",
        "summary": "No good",
        "unixReviewTime": 1486857600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "02 10, 2017",
        "reviewerID": "A1BERZJU4GD2H4",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Christine Filipski",
        "reviewText": "Love this tea!  It is not at all an overpowering ginger flavor....I use one packet of Stevia in a cup and it is delicious!",
        "summary": "Delicious tea",
        "unixReviewTime": 1486684800,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 24, 2017",
        "reviewerID": "A242BMHL25N68W",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "geofleet",
        "reviewText": "southing and tasty.",
        "summary": "Five Stars",
        "unixReviewTime": 1485216000,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "01 23, 2017",
        "reviewerID": "A8PA63C8SN4L7",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Pretty Boy",
        "reviewText": "Helps my digestion.",
        "summary": "Four Stars",
        "unixReviewTime": 1485129600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 17, 2017",
        "reviewerID": "A1ZY9X7WLE9914",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "kate boquet",
        "reviewText": "Great detox product",
        "summary": "Five Stars",
        "unixReviewTime": 1484611200,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 9, 2017",
        "reviewerID": "A3K6UFCB8C1UYN",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Brian",
        "reviewText": "tastes good and it is healthful",
        "summary": "good tea",
        "unixReviewTime": 1483920000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "12 7, 2016",
        "reviewerID": "A1RQH6PF55RRC4",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "185gal",
        "reviewText": "I don't always have fresh ginger on hand to make my own ginger tea, so this a great alternative.  It really helps to soothe my upset stomach.",
        "summary": "Great to Have on Hand for Upset Stomach!",
        "unixReviewTime": 1481068800,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "12 3, 2016",
        "reviewerID": "A3PO776XNMGCX",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Chloe",
        "reviewText": "A little spicy, but very good. I really love traditional medicinals teas. They are very good quality and I trust the company. I've used this brand for a few years and have no complaints!",
        "summary": "but very good. I really love traditional medicinals teas",
        "unixReviewTime": 1480723200,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "11 6, 2016",
        "reviewerID": "A18Z5FPM2VWMHH",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Renaiee gerber",
        "reviewText": "Super fast shipping , amazing tea and quality!",
        "summary": "Five Stars",
        "unixReviewTime": 1478390400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "10 26, 2016",
        "reviewerID": "A1GZKUU5WXSO7H",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "PennySquared",
        "reviewText": "Delicious--and potent! One tea bag is enough to add tons of flavor to a big bottle of water.",
        "summary": "Highly recommended",
        "unixReviewTime": 1477440000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "10 6, 2016",
        "reviewerID": "A23N0HOURFC3RR",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "glory",
        "reviewText": "Taste really good! My new favorite tea",
        "summary": "Taste very good!",
        "unixReviewTime": 1475712000,
    },
    {
        "overall": 4.0,
        "verified": False,
        "reviewTime": "10 5, 2016",
        "reviewerID": "A1XILZO8WHJROG",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Liz Booker",
        "reviewText": "My review of the Ginger Herbal Tea must be a vicarious one -- I sent them directly to a friend who was suffering with a sore throat.  Her thanks to me included her gratitude for the soothing, comforting cups of hot, spicy tea.  If I should catch a cold, I'll be back to buy a box of it for myself.",
        "summary": "My review of the Ginger Herbal Tea must be a ...",
        "unixReviewTime": 1475625600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "10 1, 2016",
        "reviewerID": "A1U9NCKU8OC3DQ",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Lois",
        "reviewText": "easy to use - ginger is good for your health -",
        "summary": "Five Stars",
        "unixReviewTime": 1475280000,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "08 11, 2016",
        "reviewerID": "A8OXELHHPO3TL",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "natasha",
        "reviewText": 'Well, the tea (in itself) is made & shipped great.  (Turns out that I PERSONALLY cant take Ginger Tea, but thats just me. - I love fresh ginger... )\nSo, I want to rate this tea as good, even though "MY" tastebuds don\'t really like it that much.',
        "summary": "the tea (in itself) is made & shipped great. (Turns out that I PERSONALLY cant take Ginger ...",
        "unixReviewTime": 1470873600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "08 2, 2016",
        "reviewerID": "A2E7U3TS7FZ21I",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Amazon Customer",
        "reviewText": "Love organic Ginger tea.  This one is great.",
        "summary": "Five Stars",
        "unixReviewTime": 1470096000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "05 26, 2016",
        "reviewerID": "A2QO20Z0TAHKTX",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Beverly B. Harris",
        "reviewText": "Great Medicinal Tea",
        "summary": "Five Stars",
        "unixReviewTime": 1464220800,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "05 25, 2016",
        "reviewerID": "A10C5SL817NSB7",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Linda Soto",
        "reviewText": "This is a great tasting tea.  Came on time, very well protected.  Soothes the stomach and relaxes...",
        "summary": "Relaxing Tea",
        "unixReviewTime": 1464134400,
    },
    {
        "overall": 5.0,
        "vote": "11",
        "verified": True,
        "reviewTime": "04 1, 2016",
        "reviewerID": "A330KP3CZGQMRO",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Chris Dorn",
        "reviewText": "This tastes wonderful.  Like unadulterated ginger.  So good, it can compete with ginger added to tea with a garlic press.  I'd previously bought a tea that is powder, but found it too sweet.  This is natural and in a teabag, and you can add as much or little sugar as you like.  It is nice and spicy, not watered down!  Of course, you can make it lighter by adding water, should you desire.  I find it good for nausea/tummy issues, and for a nice pick-me-up.",
        "summary": "Perfect",
        "unixReviewTime": 1459468800,
    },
    {
        "overall": 4.0,
        "vote": "2",
        "verified": True,
        "reviewTime": "02 6, 2016",
        "reviewerID": "A1JUUEH2OV5RTX",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Zelda",
        "reviewText": "7 dollars for 16 tea bags . I feel ripped off , but overall the taste is great and helps with anxiety and nauseous stomach pangs",
        "summary": "but overall the taste is great and helps with anxiety and nauseous stomach pangs",
        "unixReviewTime": 1454716800,
    },
    {
        "overall": 4.0,
        "verified": True,
        "reviewTime": "01 29, 2016",
        "reviewerID": "A2X0TUPUZUDVA9",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "stodae",
        "reviewText": "strong ginger for my tasting but thats the way gingers supposed to be. affordable price.",
        "summary": "Four Stars",
        "unixReviewTime": 1454025600,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 7, 2016",
        "reviewerID": "A2LV5H60RFCWXK",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Mikki",
        "reviewText": "love my organic",
        "summary": "Five Stars",
        "unixReviewTime": 1452124800,
    },
    {
        "overall": 5.0,
        "vote": "2",
        "verified": True,
        "reviewTime": "12 29, 2015",
        "reviewerID": "A29RS33N281XNJ",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Twain Mark",
        "reviewText": "Ginger is great, Mary Ann is kind of fun too :-)  Very good product, but you have to like Ginger and the good things it does for you. Would buy again.",
        "summary": "Ginger is great, Mary Ann is kind of fun too",
        "unixReviewTime": 1451347200,
    },
    {
        "overall": 2.0,
        "verified": True,
        "reviewTime": "11 17, 2015",
        "reviewerID": "AT0NUNDO8THHP",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Amazon Customer",
        "reviewText": "Service was excellent but I just don't care for the flavor of ginger tea.",
        "summary": "Two Stars",
        "unixReviewTime": 1447718400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "10 8, 2015",
        "reviewerID": "A2ZP7F2XXKGUCR",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "S. Block",
        "reviewText": "When nothing else works for nausea, I turn to ginger tea.  Since I had none, I ordered this tea.  It has a really good flavor, doesn't irritate my stomach, and was delivered pronto.",
        "summary": "Really nice ginger tea",
        "unixReviewTime": 1444262400,
    },
    {
        "overall": 2.0,
        "verified": True,
        "reviewTime": "09 23, 2015",
        "reviewerID": "A1M5D12C0PGGLI",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Kris",
        "reviewText": "I gave it to a friend to halt the beginning of a migraine.  She said it worked but the taste is so horrid, she'll never drink it again.",
        "summary": "Helpful for migraines but horrid taste!",
        "unixReviewTime": 1442966400,
    },
    {
        "overall": 5.0,
        "vote": "3",
        "verified": True,
        "reviewTime": "05 16, 2015",
        "reviewerID": "A14RJBUEYG5OYY",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Renee&#039; France Mihld",
        "reviewText": "Very happy to find Ginger Tea, and the fact that is organic is even better. The flavor is great, and I also add a bag in with another flavor such as Burdock Root to make that taste better.  The packaging is great and has alot of great information. The quality is above my high standards and I will be buying this again.\n\nWhen you use this tea, steep it for as long as recommended - and then make sure you squeeze out the bag to get all the greatness out.",
        "summary": "Ginger Tea that tastes great",
        "unixReviewTime": 1431734400,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "02 11, 2015",
        "reviewerID": "A2SC934PYWH4G",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "diane griesser",
        "reviewText": "Very tasty--just the right zing and great for opening my sinuses when I have a cold.",
        "summary": "Five Stars",
        "unixReviewTime": 1423612800,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "01 17, 2015",
        "reviewerID": "A3KZIIIYT3ATNL",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Kathy 26",
        "reviewText": "I love Ginger tea. I have a cup every morning with raw honey and lemon juice. I like that this one is organic.",
        "summary": "Great product",
        "unixReviewTime": 1421452800,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "11 5, 2014",
        "reviewerID": "A14VEJF020O9D2",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Lucille",
        "reviewText": "This is the best ginger tea I've found anywhere.  Not weak but not too strong either, plain or with a little dash of honey...Perfect.",
        "summary": "The best ginger tea anywhere",
        "unixReviewTime": 1415145600,
    },
    {
        "overall": 5.0,
        "verified": False,
        "reviewTime": "10 22, 2014",
        "reviewerID": "A1I2LBMX4XL9AQ",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 16 Wrapped Tea Bags"},
        "reviewerName": "Lisa ",
        "reviewText": "Great tea!",
        "summary": "Refreshing!",
        "unixReviewTime": 1413936000,
    },
    {
        "overall": 5.0,
        "verified": True,
        "reviewTime": "04 7, 2018",
        "reviewerID": "A253RBNRYT1H3E",
        "asin": "B0009JQK9C",
        "style": {"Size:": " 32 Bags"},
        "reviewerName": "Fieldem",
        "reviewText": "Love this tea!",
        "summary": "Five Stars",
        "unixReviewTime": 1523059200,
    },
]
