name: Tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.11", os: "ubuntu-latest", session: "safety" }
          - { python: "3.11", os: "ubuntu-latest", session: "mypy-3.11" }
          - { python: "3.9", os: "ubuntu-latest", session: "mypy-3.9" }
          - { python: "3.8", os: "ubuntu-latest", session: "mypy-3.8" }
          - { python: "3.10", os: "ubuntu-latest", session: "mypy-3.10" }
          - { python: "3.11", os: "ubuntu-latest", session: "tests-3.11" }
          - { python: "3.9", os: "ubuntu-latest", session: "tests-3.9" }
          - { python: "3.8", os: "ubuntu-latest", session: "tests-3.8" }
          - { python: "3.10", os: "ubuntu-latest", session: "tests-3.10" }
          - { python: "3.11", os: "macos-latest", session: "tests-3.11" }
          - { python: "3.11", os: "ubuntu-latest", session: "xdoctest-3.11" }
          - { python: "3.11", os: "ubuntu-latest", session: "docs-build" }

    env:
      NOXSESSION: ${{ matrix.session }}
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.6.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install pre-requisities
        run: make install-poetry

      - name: Run Nox
        run: make run-nox-session

      - name: Upload coverage data
        if: always() && matrix.session == 'tests-3.11'
        uses: "actions/upload-artifact@v3"
        with:
          name: coverage-data
          path: ".coverage.*"

      - name: Upload documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.11"

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Install dependencies
        run: |
          make install-poetry

      - name: Combine coverage data and display human readable report
        run: |
          NOXSESSION=coverage make run-nox-session

      - name: Create coverage report
        run: |
          NOXSESSION='coverage -- xml' make run-nox-session

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.2
